### PR TITLE
Fix - empty activity list when course include Label resources

### PR DESCRIPTION
**Pull request by nadavkav**
- minor fix/migration of deprecated function get_courseid_from_context() call with get_course_context()

### CODE REVIEW

**Comment by danpoltawski** [comment]
Hi Nadav,

Thanks for the patch, but I don't think your should do a hardcoded check for label, instead do:

```
if (!$cm->uservisible or !$cm->has_view()) {
```

**Comment by nadavkav** [comment]
You are right! even better. Thanks :-)

**Comment by nadavkav** [comment]
Updated the patch (PR)

**Comment by danpoltawski** [comment]
Thanks, merged (I squashed your commits):
https://github.com/danpoltawski/moodle-repository_activitylinks/commit/9e08c21dbb3ac03f52db37b5fd16d097dde26d2e

**Comment by nadavkav** [comment]
Nothing taste better than a good squash ;-)

**Comment by nadavkav** [comment]
btw, why not put this useful repository plugin on Moodle's plugin database?

**Comment by danpoltawski** [comment]
Martin told me that filter_activitynames in core is kind of the meant to do this :)

**Comment by nadavkav** [comment]
But this is for cases where you do not want to turn filter_activitynames on, and have direct links to selected activities. weird.

(I have modified a theme we are using that shows only the page's content when we put links of course activities and resources into the contrib mod_tab pages (tabs). teachers love it. and your plugin helps them select the activities easily instead of copy&pasting them from the course's main page)

**Pull request closed without merging**
